#pragma once
#include "activitate.h"
#include "repo.h"
#include "service.h"
#include "validator.h"
#include <assert.h>

void testAll();
void test_activitate();
void test_adaugare_repo();
void test_actualizare_repo();
void test_stergere_repo();
void test_cmp();
void test_actualizare_service();
void test_stergere_service();
void test_adaugare_service();
void test_gaseste_repo();
void test_cautare_service();
void test_filtrare();
void test_sortare();
void test_adaugare_lista_repo();
void test_golire_lista_repo();
void test_generare_lista_repo();
void test_adaugare_lista_service();
void test_golire_lista_service();
void test_generare_lista_service();
void test_get_marime_lista();
void test_cerinta_noua();
void test_dto();
void test_undo();
void test_validare_fisier();
void test_export_cos_csv();
void test_export_cos_html();